### ISSUE TITLE
cookie 或 projectId 配置错误

### ISSUE THREAD

**Issue by if1y** [FlxSNX/TeambitionShare#1]
试了很多次，cookie 和 id 肯定没问题，不知道怎么回事。
本来以为是团队版和个人版的区别，但是切换过来依然不行。

**Comment by FlxSNX** [comment]
方便给我账号或者cookie 测试看看吗

**Comment by if1y** [comment]
看起来是虚拟主机的问题，调用了什么被禁用的参数？换到另一台就正常了

**Comment by FlxSNX** [comment]
我是没用什么禁用的函数的，在获取项目信息时就报错 可能是虚拟主机禁用了curl？

**Comment by if1y** [comment]
可能是吧，问题不大，不用虚拟主机了~
