### ISSUE TITLE
希望可以添加自定义标题背景和文件夹等颜色~

### ISSUE THREAD

**Issue by andrewjr1991** [FlxSNX/TeambitionShare#14]
希望可以添加自定义标题背景和文件夹等颜色~全黑的虽然很简洁，很庄重，但是还是想要活泼一点，比如跟Teambition一样的蓝色？

**Comment by FlxSNX** [comment]
不打算增加自定义颜色,但Teambition那种蓝色貌似好看一点,已经改成蓝色了
![image](https://user-images.githubusercontent.com/34613385/103299987-ce052600-4a38-11eb-91ea-322de64cb45a.jpg)

**Comment by FlxSNX** [comment]
在下一个版本中改成蓝色

**Comment by andrewjr1991** [comment]
谢谢！新版很好看哦！！！
