### ISSUE TITLE
进入文件夹提示“404 Not Found”

### ISSUE THREAD

**Issue by Jacky-Bruse** [FlxSNX/TeambitionShare#2]
获取Cookie和项目ID 填到config/app.cfg.php中，网站也好了，现在可以顺利进入网站，但是打开任何以个文件夹会提示“404 Not Found  --nginx”请问是哪里有错误吗？

**Comment by Jacky-Bruse** [comment]
![Uploading 1.jpg…]()

**Comment by FlxSNX** [comment]
需要配置伪静态 nginx的伪静态规则在nginx文件中

**Comment by Jacky-Bruse** [comment]
> 需要配置伪静态nginx的伪静态规则在nginx文件中

请问有相关教程吗？门外汉，兴趣使然，感谢大佬的快速恢复，谢谢

**Comment by FlxSNX** [comment]
https://www.php.cn/nginx/432468.html

**Comment by FlxSNX** [comment]
如果服务器用的是宝塔面板 直接在站点设置 - 伪静态 中配置

**Comment by Jacky-Bruse** [comment]
弄出来了，谢谢大佬，很给力
