### ISSUE TITLE
配置项目的时候，会出现一个默认文件夹，然后删不掉

### ISSUE THREAD

**Issue by andrewjr1991** [FlxSNX/TeambitionShare#25]
配置项目的时候，会出现一个默认文件夹，然后删不掉，项目中没有，但是配置的时候一直出现，点进去就是该页面已丢失，不清楚为啥
![image](https://user-images.githubusercontent.com/20033630/103543610-cb437e80-4ed9-11eb-918e-6a3bc72ef25b.png)
![image](https://user-images.githubusercontent.com/20033630/103543636-d72f4080-4ed9-11eb-9b23-094b8847b7d6.png)

**Comment by FlxSNX** [comment]
这我也很懵，我没弄默认文件夹啊

**Comment by andrewjr1991** [comment]
> 这我也很懵，我没弄默认文件夹啊

嗯嗯，很奇怪，我用了以前的版本后是正常的，就是最新版会出现这个
