### ISSUE TITLE
二级目录下的链接路径问题

### ISSUE THREAD

**Issue by if1y** [FlxSNX/TeambitionShare#3]
程序运行在二级目录的时候，跳转的链接会缺少二级目录
如 `https://domain.com/sub/xxxxxxxxxx` 变成 `https://domain.com/xxxxxxxxxx`

**Comment by FlxSNX** [comment]
好的,问题将在下个版本修复

**Comment by FlxSNX** [comment]
1.1已支持二级目录运行,就是伪静态规则需要对应的修改一下

**Comment by if1y** [comment]
新版 二级目录下报错
`Error Code:500 配置错误 [类型只能为project或pan]`

另外你的仓库和 release 发布时都遗漏了 `config/app.cfg.php` 文件

**Comment by FlxSNX** [comment]
并不是遗漏了app.cfg.php文件，新版增加了配置向导，通过配置向导生成app.cfg.php文件，不再手动填写

你删除app.cfg.php 文件 然后通过配置向导重新生成配置文件即可

**Comment by if1y** [comment]
嗷嗷原来是这样，搞定了。

我把`.htaccess `放在二级目录，然后没作调整就正常了

**Comment by FlxSNX** [comment]
嗯嗯好的，nginx的话需要修改
