### ISSUE TITLE
请问可以支持目录密码/全局登录密码吗？

### ISSUE THREAD

**Issue by SagiriShiho** [FlxSNX/TeambitionShare#4]
想在小圈子里分享文件，不太想完全公开
列如在目录里识别.passwd文件内容作为单独目录密码，又或者直接一个全局登录密码
最后非常感谢作者的项目

**Comment by FlxSNX** [comment]
下次更新会加上

**Comment by FlxSNX** [comment]
1.1已增加全局访问密码,目录密码后续再更新

**Comment by SagiriShiho** [comment]
> 1.1已增加全局访问密码,目录密码后续再更新

好的，非常感谢作者
