### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Jacky-Bruse** [FlxSNX/TeambitionShare#7]
config/app.cfg.php
这个文件不见了，大佬，是不是有问题？

**Comment by FlxSNX** [comment]
app.cfg.php 现在通过配置向导生成

**Comment by Jacky-Bruse** [comment]
再次请教大佬教程，不太会，学习，谢谢

**Comment by FlxSNX** [comment]
就是没填写配置时 会自动跳转到配置向导 在配置向导页面填写对应的东西 就可以生成了

**Comment by Jacky-Bruse** [comment]
我还以为不小心漏了呢，现在会操作了，谢谢指导
